config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('subscribe/',include('subscribe.urls')),
    path ('',include('posts.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path ,re_path
from .views import *


app_name="posts"
urlpatterns = [
    path('', index.as_view()),
    path ('category/<slug:slug>',listofcategory,name="listed-by-cat"),
    path ('about',about,name="about_me"),

    
    #path('single', single),
    re_path(r'post/(?P<slug>[-\w]+)/',single,name="single"),
    path ('search',searchView,name= 'post_search'),
]

subscribe/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import  *
from django.urls import path

app_name ="subscribe"
urlpatterns =[
    path('add',SubView,name='send_email'),
    path('confirm/',ConfirmView,name='confirm'),
    #path('remove'),
    


]

templates/confirme.html
{% extends 'base.html'%}
{%block title %} main page{% endblock%}
{% load static %}




        {% block content %}
        <section class="section lb m3rem">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            خیلی خوشحالیم که با ما همراهی کردی
                            
                        </div>
                    </div>
                </div>
            </div>

        {% endblock %}

templates/header.html
{% load static%}

<header class="market-header header">
    <div class="container-fluid">
        <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="{% static 'images/version/logo.png' %}" alt=""></a>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    {% if cats %} 
                    
                    {% for cat in cats %}
                    <li class="nav-item">
                        <a class="nav-link" href= "{{cat.get_absolute_url }}">{{cat.name}}</a>
                    </li>
                    {% endfor %}
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:about_me' %}">درباره من</a>
                    </li>

                </ul>
                <form class="form-inline" method="GET" action = "{% url 'posts:post_search' %}">
                    {{ searchform.as_p }}
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">جستجو</button>
                </form>
            </div>
        </nav>
    </div><!-- end container-fluid -->
</header><!-- end market-header -->

templates/index.html
{% extends 'base.html'%}
{%block title %} main page{% endblock%}
{% load static %}
{% load jalali_tags %}

{% block content %}

        <section id="cta" class="section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12 align-self-center">
                        
                        <p class="lead">  وجیهه حسینی هستم <br>و در این وبسایت شخصی داستان های کوتاه و نوشته های خودم رو در اشتراک میگذارم</p>
                        
                    </div>
                    <div class="col-lg-4 col-md-12">
                        {% include "newletter.html"%}
            

                    </div>
                </div>
            </div>
        </section>

        <section class="section lb" dir="rtl">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            <div class="blog-custom-build">
                                {% for obj in object_list%}
                                <div class="blog-box wow fadeIn">
                                    <div class="post-media">
                                        <a href="{%url 'posts:single'  obj.slug %}" title="">
                                            
                                            <img src="{{obj.img_url}}" alt="" class="img-posts ">
                                            
                                            <div class="hovereffect">
                                                <span></span>
                                            </div>
                                            <!-- end hover -->
                                        </a>
                                    </div>
                                    <!-- end media -->
                                    <div class="blog-meta big-meta text-center">
                                        <div class="post-sharing">
                                            <ul class="list-inline">
                                                <li><a href="#" class="fb-button btn btn-primary"><i class="fa fa-whatsapp"></i> <span class="down-mobile"></a>
                                                    <a href="#" class="tw-button btn btn-primary"><i class="fa fa-twitter"></i> <span class="down-mobile"></a>
                                                    <a href="#" class="gp-button btn btn-primary"><i class="fa fa-google"></i></a></li>
                                            </ul>
                                        </div><!-- end post-sharing -->
                                        <h4><a href="{% url 'posts:single'  obj.slug %}" title="">{{obj.title}}</a></h4>
                                        <p>{{ obj.body|safe|striptags|truncatewords:30}}}</p>
                                        
                                        <small> نوشته شده در تاریخ{{obj.publish|to_jalali:'%y/%m/%d ساعت %H:%M:%S'}}</small>
                                        <small><a href="{% url 'posts:about_me'%}" title=""> توسط {{obj.auther.get_full_name}}</a></small>
                                        
                                    </div><!-- end meta -->
                                </div><!-- end blog-box -->

                                <hr class="invis">
                                {% endfor %}



                            </div>
                        </div>

                        <hr class="invis">

                        <div class="row">
                            <div class="col-md-12">
                                <nav aria-label="Page navigation">
                                    {% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item disabled"><a class ="page-link ">{{i}}</a></li>
      {% else %}
        <li class = "page-item"><a  class = "page-link"href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

                                </nav>
                            </div><!-- end col -->
                        </div><!-- end row -->
                    </div><!-- end col -->
                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="sidebar">


                            <div class="widget">

                                <h4 class="widget-title" dir="rtl">نوشته های اخیر</h4>
                                <div class="blog-list-widget">
                                    <div class="list-group">
                                         <!-- Slideshow container -->
                                            <div class="slideshow-container">
                                            {% for n in nots_list%}
                                            <!-- Full-width slides/quotes -->
                                            <div class="mySlides">
                                                <q>{{n.body}}</q>
                                                
                                            </div>
                                            {% endfor %}
                                            <!-- Next/prev buttons -->
                                            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                                            <a class="next" onclick="plusSlides(1)">&#10095;</a>
                                            </div>
                                            <!-- Dots/bullets/indicators -->
                                            
                                            <div class="dot-container">
                                            {% for n in count %}
                                            <span class="dot" onclick="currentSlide('{{n}}')"></span>

                                            {% endfor %}
                                            </div> 
 

                
        
                                        </div>
                                     </div><!-- end blog-list -->
                                </div><!-- end widget -->

                            <div id="" class="widget">
                                <h2 class="widget-title">تبلیغات</h2>
                                <div class="banner-spot clearfix">
                                    <div class="banner-img">
                                        <img src="upload/banner_03.jpg" alt="" class="img-fluid">
                                    </div><!-- end banner-img -->
                                </div><!-- end banner -->
                            </div><!-- end widget -->

 

                            <div class="widget">
                                <h2 class="widget-title">محبوب ترین نوشته ها</h2>
                                <div class="link-widget">
                                    <ul>
                                        <li><a href="#">Marketing <span>(21)</span></a></li>
                                    </ul>
                                </div><!-- end link-widget -->
                            </div><!-- end widget -->
                        </div><!-- end sidebar -->
                    </div><!-- end col -->



                </div><!-- end row -->
            </div><!-- end container -->
        </section>

    {% endblock %}

  

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}




        {% block content %}

        <section class="section lb m3rem" dir="rtl">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            <div class="blog-custom-build">
                                {% for obj in object_list %}
                                <div class="blog-box wow fadeIn">
                                    <div class="post-media">
                                        <a href="{%url 'posts:single'  obj.slug %}" title="">
                                           
                                            <img src="{{obj.img_url }}" alt="" class="img-posts ">
                                            
                                            <div class="hovereffect">
                                                <span></span>
                                            </div>
                                            <!-- end hover -->
                                        </a>
                                    </div>
                                    <!-- end media -->
                                    <div class="blog-meta big-meta text-center">
                                        <div class="post-sharing">
                                            <ul class="list-inline">
                                                <li><a href="#" class="fb-button btn btn-primary"><i class="fa fa-whatsapp"></i> <span class="down-mobile"></a>
                                                    <a href="#" class="tw-button btn btn-primary"><i class="fa fa-twitter"></i> <span class="down-mobile"></a>
                                                    <a href="#" class="gp-button btn btn-primary"><i class="fa fa-google"></i></a></li>

                                            </ul>
                                        </div><!-- end post-sharing -->
                                        <h4><a href="{% url 'posts:single'  obj.slug %}" title="">{{obj.title}}</a></h4>
                                        <p>{{ obj.body|safe|striptags|truncatewords:30}}}</p>

                                        <small><a href="" title="">{{obj.publish|to_jalali:'%y/%m/%d ساعت %H:%M:%S'}}</a></small>
                                        <small><a href="{% url 'posts:about_me'%}" title=""> نویسنده : {{obj.auther.get_full_name}}</a></small>
                                        
                                    </div><!-- end meta -->
                                </div><!-- end blog-box -->

                                <hr class="invis">
                                {% endfor %}



                            </div>
                        </div>

                        <hr class="invis">

                        <div class="row">
                            <div class="col-md-12">
                                <nav aria-label="Page navigation">

                                {% if object_list.has_other_pages %}
                                    <ul class="pagination justify-content-center">
                                        {% if object_list.has_previous %}
                                        <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}
                                        {% for i in object_list.paginator.page_range %}
                                        {% if object_list.number == i%}
                                        <li class="page-item disabled"><a  class = "page-link">{{ i }}</a> </li>
                                        {% else %}
                                          <li class="page-item"><a  class = "page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                        {% endfor %}

                                      {% if object_list.has_next %}
                                      <li><a href="?page={{ object_list.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                      <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                        


                                    </ul>
                                {% endif %}
                                </nav>
                            </div><!-- end col -->
                        </div><!-- end row -->
                    </div><!-- end col -->
                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="sidebar">


                            <div class="widget">
                                {% include "newletter.html" %}
                                <h2 class="widget-title">نوشته های اخیر</h2>
                                <div class="blog-list-widget">
                                    <div class="list-group">
                                        {% for p in newPosts%}
                                        <a href="{{p.get_absolute_url}}" class="list-group-item list-group-item-action flex-column align-items-start">
                                            <div class="w-100 last-item justify-content-between">
                                                <img src="{{p.img_url}}" alt="" class="img-fluid float-left">
                                                <h5 class="mb-1">{{p.title}}</h5>
                                                <small>{{p.publish|to_jalali:'%y/%m/%d _ %H:%M:%S'}}</small>
                                            </div>
                                        </a>
                                        {% endfor %}
 

          


                                    </div>
                                </div><!-- end blog-list -->
                            </div><!-- end widget -->

                            <div id="" class="widget">
                                <h2 class="widget-title">Advertising</h2>
                                <div class="banner-spot clearfix">
                                    <div class="banner-img">
                                        <img src="upload/banner_03.jpg" alt="" class="img-fluid">
                                    </div><!-- end banner-img -->
                                </div><!-- end banner -->
                            </div><!-- end widget -->

                            <div class="widget">
                                <h2 class="widget-title">Instagram Feed</h2>
                                <div class="instagram-wrapper clearfix">
                                    <a class="" href="#"><img src="upload/small_09.jpg" alt="" class="img-fluid"></a>
                                    <a href="#"><img src="upload/small_01.jpg" alt="" class="img-fluid"></a>

                                    <a href="#"><img src="upload/small_08.jpg" alt="" class="img-fluid"></a>
                                </div><!-- end Instagram wrapper -->
                            </div><!-- end widget -->

                            <div class="widget">
                                <h2 class="widget-title">Popular Categories</h2>
                                <div class="link-widget">
                                    <ul>
                                        <li><a href="#">Marketing <span>(21)</span></a></li>
                                    </ul>
                                </div><!-- end link-widget -->
                            </div><!-- end widget -->
                        </div><!-- end sidebar -->
                    </div><!-- end col -->

 


                </div><!-- end row -->
            </div><!-- end container -->
        </section>
        {% endblock %}

templates/newletter.html
<div class="newsletter-widget text-center align-self-center">
    <h3>جدید ترین نوشته ها رو دریافت کنید</h3>
    <p>ایمیل خودتون رو وارد کنید تا هر نوشته جدید سایت رو براتون ارسال کنیم</p>
    <form class="" method="post" action="{% url  'subscribe:send_email' %}">
    
    {% csrf_token %}
    {{ form.as_p }}
        <input type="submit" value="ارسال" class="btn btn-default " style="margin-top: 10%;" />
    </form>         
</div><!-- end newsletter -->

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_tags %}




        {% block content %}

        <section class="section lb m3rem">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            <div class="blog-custom-build">
                                {% for obj  in  results %}
                                <div class="blog-box wow fadeIn">
                                    <div class="post-media">
                                        <a href="{%url 'posts:single'  obj.slug %}" title=""></a>

                                            <div class="hovereffect">
                                                <span></span>
                                            </div>
                                            <!-- end hover -->
                                        </a>
                                    </div>
                                    <!-- end media -->
                                    <div class="blog-meta big-meta text-center">
                                       
                                        <h4><a href="{% url 'posts:single'  obj.slug %}" title="">{{obj.title}}</a></h4>
                                        <p>{{ obj.body|safe|striptags|truncatewords:30}}}</p>
                                        <small><a href="marketing-category.html" title="">Make Money</a></small>
                                        <small><a href="marketing-single.html" title="">24 July, 2017</a></small>
                                        <small><a href="#" title="">by Jack</a></small>
                                        <small><a href="#" title=""><i class="fa fa-eye"></i> 2291</a></small>
                                    </div><!-- end meta -->
                                </div><!-- end blog-box -->

                                <hr class="invis">
                                {% endfor %}



                            </div>
                        </div>

                        <hr class="invis">

                        <div class="row">
                            <div class="col-md-12">
                                <nav aria-label="Page navigation">
                                    <ul class="pagination justify-content-center">
                                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item">
                                            <a class="page-link" href="#">Next</a>
                                        </li>
                                    </ul>
                                </nav>
                            </div><!-- end col -->
                        </div><!-- end row -->
                    </div><!-- end col -->
                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="sidebar">


                            <div class="widget">
                                {% include "newletter.html" %}
                                <h2 class="widget-title">Recent Posts</h2>
                                <div class="blog-list-widget">
                                    <div class="list-group">
 

          

                                        <a href="marketing-single.html" class="list-group-item list-group-item-action flex-column align-items-start">
                                            <div class="w-100 last-item justify-content-between">
                                                <img src="upload/small_09.jpg" alt="" class="img-fluid float-left">
                                                <h5 class="mb-1">Did you see the most beautiful sea in the world?</h5>
                                                <small>07 Jan, 2016</small>
                                            </div>
                                        </a>
                                    </div>
                                </div><!-- end blog-list -->
                            </div><!-- end widget -->

                            <div id="" class="widget">
                                <h2 class="widget-title">Advertising</h2>
                                <div class="banner-spot clearfix">
                                    <div class="banner-img">
                                        <img src="upload/banner_03.jpg" alt="" class="img-fluid">
                                    </div><!-- end banner-img -->
                                </div><!-- end banner -->
                            </div><!-- end widget -->

                            <div class="widget">
                                <h2 class="widget-title">Instagram Feed</h2>
                                <div class="instagram-wrapper clearfix">
                                    <a class="" href="#"><img src="upload/small_09.jpg" alt="" class="img-fluid"></a>
                                    <a href="#"><img src="upload/small_01.jpg" alt="" class="img-fluid"></a>

                                    <a href="#"><img src="upload/small_08.jpg" alt="" class="img-fluid"></a>
                                </div><!-- end Instagram wrapper -->
                            </div><!-- end widget -->

                            <div class="widget">
                                <h2 class="widget-title">Popular Categories</h2>
                                <div class="link-widget">
                                    <ul>
                                        <li><a href="#">Marketing <span>(21)</span></a></li>
                                    </ul>
                                </div><!-- end link-widget -->
                            </div><!-- end widget -->
                        </div><!-- end sidebar -->
                    </div><!-- end col -->

 


                </div><!-- end row -->
            </div><!-- end container -->
        </section>
        {% endblock %}

templates/sidebar.html
                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                        <div class="sidebar">


                            <div class="widget">
                                <div class="newsletter-widget text-center align-self-center">
                                    <h3>Subscribe Today!</h3>
                                    <p>Subscribe to our weekly Newsletter and receive updates via email.</p>
                                    <form class="form-inline" method="post" action="{% url  'subscribe:send_email' %}">
                                    
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                        <input type="submit" value="ارسال" class="btn btn-default btn-block" />
                                    </form>         
                                </div><!-- end newsletter -->
                                <h2 class="widget-title">نوشته ها</h2>
                                <div class="blog-list-widget">
                                    <div class="list-group">
 

          

                                        <a href="marketing-single.html" class="list-group-item list-group-item-action flex-column align-items-start">
                                            <div class="w-100 last-item justify-content-between">
                                                <img src="upload/small_09.jpg" alt="" class="img-fluid float-left">
                                                <h5 class="mb-1">Did you see the most beautiful sea in the world?</h5>
                                                <small>07 Jan, 2016</small>
                                            </div>
                                        </a>
                                    </div>
                                </div><!-- end blog-list -->
                            </div><!-- end widget -->

                            <div id="" class="widget">
                                <h2 class="widget-title">Advertising</h2>
                                <div class="banner-spot clearfix">
                                    <div class="banner-img">
                                        <img src="upload/banner_03.jpg" alt="" class="img-fluid">
                                    </div><!-- end banner-img -->
                                </div><!-- end banner -->
                            </div><!-- end widget -->

                            <div class="widget">
                                <h2 class="widget-title">Instagram Feed</h2>
                                <div class="instagram-wrapper clearfix">
                                    <a class="" href="#"><img src="upload/small_09.jpg" alt="" class="img-fluid"></a>
                                    <a href="#"><img src="upload/small_01.jpg" alt="" class="img-fluid"></a>

                                    <a href="#"><img src="upload/small_08.jpg" alt="" class="img-fluid"></a>
                                </div><!-- end Instagram wrapper -->
                            </div><!-- end widget -->

                            <div class="widget">
                                <h2 class="widget-title">Popular Categories</h2>
                                <div class="link-widget">
                                    <ul>
                                        <li><a href="#">Marketing <span>(21)</span></a></li>
                                    </ul>
                                </div><!-- end link-widget -->
                            </div><!-- end widget -->
                        </div><!-- end sidebar -->
                    </div><!-- end col -->